### ISSUE TITLE
Error: undefined:980:1: selector missing

### ISSUE THREAD

**Issue by sylrs** [purifycss/purifycss#163]
`Sylvians-Macbook-Pro:phonic-site sylvian$ purifycss css/style.css index.html --out css/style-purified.css --info
/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:72
      throw err;
      ^

Error: undefined:980:1: selector missing
    at error (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:62:15)
    at rule (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:554:22)
    at rules (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:117:70)
    at stylesheet (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:81:21)
    at module.exports (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:564:20)
    at rework (/usr/local/lib/node_modules/purify-css/node_modules/rework/index.js:27:21)
    at CssTreeWalker.beginReading (/usr/local/lib/node_modules/purify-css/lib/purifycss.js:568:24)
    at purify (/usr/local/lib/node_modules/purify-css/lib/purifycss.js:1009:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/purify-css/bin/purifycss:54:5)
    at Module._compile (module.js:571:32)
`

**Comment by Ffloriel** [comment]
Hey,
Can you provide the files used?
It will help determine the problem.

**Comment by sylrs** [comment]
Sure, I have uploaded an archive here:

[html & css.zip](https://github.com/purifycss/purifycss/files/1020144/html.css.zip)

**Comment by Ffloriel** [comment]
Thanks for the files.
The problem is line 990 in the css file. There is no selector there and it is not considered valid css.
```css
{
  color: #c2344f
}
```
You can put a random class as the selector. Purifycss will remove it anyway.
```css
.qwertyuiop {
  color: #c2344f
}
```

**Comment by sylrs** [comment]
Oh wow, thanks! It finally works now.
