### ISSUE TITLE
Critical dependency warning because of uglify-js

### ISSUE THREAD

**Issue by rolele** [purifycss/purifycss#174]
I am using purifycss but now I am seing a warning in my webpack because of one of your dependency.

```
../~/uglify-js/tools/node.js
24:11-32 Critical dependency: the request of a dependency is an expression
    at RequireResolveContextDependency.getWarnings (/Users/others/wishlist/client/wishlist-client/node_modules/webpack/lib/dependencies/RequireResolveContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/others/wishlist/client/wishlist-client/node_modules/webpack/lib/Compilation.js:672:24)
    at Compilation.finish (/Users/others/wishlist/client/wishlist-client/node_modules/webpack/lib/Compilation.js:535:9)
    at /Users/others/wishlist/client/wishlist-client/node_modules/webpack/lib/Compiler.js:491:16
    at /Users/others/wishlist/client/wishlist-client/node_modules/webpack/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/others/wishlist/client/wishlist-client/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/others/wishlist/client/wishlist-client/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
The point here is that from that point webpack is unable to optimize the import and you endup with the whole js in your final bundle.
```
I open a ticket there but it was pretty useless:
https://github.com/mishoo/UglifyJS2/issues/2115

Are you seing the same warning?

**Comment by Ffloriel** [comment]
What is the version of purifycss that you are using?

**Comment by rolele** [comment]
```
purify-css@1.2.5
webpack@2.6.1
$ node --version                                                                                                                                                                                                                  
v8.1.2
```
yes it still does

**Comment by Ffloriel** [comment]
Maybe you should report the issue to this [repository](https://github.com/webpack-contrib/purifycss-webpack) as it is more related to webpack.

**Comment by Snazzyham** [comment]
I'm getting the same issue when I try using just the CLI without webpack. Tried installing `uglify-js` globally as well, still getting the same issue. Seems to be an issue with the Purifycss dependency itself.
