### ISSUE TITLE
*Error* Selector missing

### ISSUE THREAD

**Issue by emphaticsunshine** [purifycss/purifycss#179]
I am getting following error when I run purifycss through webpack:
```
Error: undefined:390:2: selector missing
    at error (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:62:15)
    at rule (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:554:22)
    at rules (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:117:70)
    at stylesheet (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:81:21)
    at module.exports (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:564:20)
    at rework (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/rework/index.js:27:21)
    at CssTreeWalker.beginReading (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/purify-css/lib/purifycss.js:568:24)
    at purify (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/purify-css/lib/purifycss.js:1009:10)
    at Compilation.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/purifycss-webpack-plugin/index.js:52:32)
    at Compilation.next (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:69:14)
    at ExtractTextPlugin.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/index.js:309:4)
    at Compilation.applyPluginsAsync (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/index.js:285:5)
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:209:22)
    at ExtractTextPlugin.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/index.js:237:10)
    at Compilation.applyPluginsAsync (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.seal (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:417:12
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:332:10
Error: undefined:390:2: selector missing
    at error (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:62:15)
    at rule (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:554:22)
    at rules (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:117:70)
    at stylesheet (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:81:21)
    at module.exports (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/css/lib/parse/index.js:564:20)
    at rework (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/rework/index.js:27:21)
    at CssTreeWalker.beginReading (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/purify-css/lib/purifycss.js:568:24)
    at purify (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/purify-css/lib/purifycss.js:1009:10)
    at Compilation.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/purifycss-webpack-plugin/index.js:52:32)
    at Compilation.next (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:69:14)
    at ExtractTextPlugin.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/index.js:309:4)
    at Compilation.applyPluginsAsync (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/index.js:285:5)
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:209:22)
    at ExtractTextPlugin.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/extract-text-webpack-plugin/index.js:237:10)
    at Compilation.applyPluginsAsync (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.seal (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:417:12
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/mseth1/Projects/yoda-microsite-pdp/node_modules/webpack/lib/Compilation.js:332:10
```

My webpack script related to this piece is as follow:

```javascript
const productionPlugins = [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
        compress: {
            unused: true,
            dead_code: true,
            warnings: false,
        },
    }),
    new purify({
        basepath: process.cwd(),
        paths: glob.sync('/src/components/**/*.jsx'),
        resolveExtensions: ['jsx', 'js'],
        purifyOptions: {
            info: true,
            whitelist: ['*purify*'],
        },
    })
];
```

Any help is appreciated.

**Comment by dertin** [comment]
- purifycss 1.2.6
- mac 10.13.1

Command:
`purifycss css/main.css css/libs.css js/default.js index.html index2.html --info --out css/style.css`

Error:
```
/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:72
      throw err;
      ^

Error: undefined:831:1: selector missing
    at error (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:62:15)
    at rule (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:554:22)
    at rules (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:117:70)
    at atmedia (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:380:35)
    at atrule (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:534:10)
    at rules (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:117:58)
    at stylesheet (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:81:21)
    at module.exports (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:564:20)
    at rework (/usr/local/lib/node_modules/purify-css/node_modules/rework/index.js:27:21)
    at CssTreeWalker.beginReading (/usr/local/lib/node_modules/purify-css/lib/purifycss.js:568:24)
```
