### ISSUE TITLE
purify css wont run without stacktrace

### ISSUE THREAD

**Issue by benoj** [purifycss/purifycss#185]
node -v `v8.1.2`

```
purifycss ./src/server/static/css/index.css ~/Desktop/content.html                                         ✓  7005  13:33:40
/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:72
      throw err;
      ^

Error: undefined:2289:2: missing '{'
    at error (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:62:15)
    at declarations (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:247:25)
    at rule (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:560:21)
    at rules (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:117:70)
    at stylesheet (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:81:21)
    at module.exports (/usr/local/lib/node_modules/purify-css/node_modules/css/lib/parse/index.js:564:20)
    at rework (/usr/local/lib/node_modules/purify-css/node_modules/rework/index.js:27:21)
    at CssTreeWalker.beginReading (/usr/local/lib/node_modules/purify-css/lib/purifycss.js:568:24)
    at purify (/usr/local/lib/node_modules/purify-css/lib/purifycss.js:1009:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/purify-css/bin/purifycss:63:17)
```

**Comment by bonebizz21** [comment]
Cool

**Comment by virajsinha** [comment]
Was there any resolution to this issue?
